name: Deploy Documentation

on:
  workflow_call:
    inputs:
      DOC_TAG:
        required: true
        type: string

jobs:
  build:
    uses: ./.github/workflows/_build_docs.yaml
    with:
      DOC_TAG: ${{ inputs.DOC_TAG }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download Documentation Artifact
        uses: actions/download-artifact@v4
        with:
          name: documentation-latest
          path: docs/_build/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          destination_dir: ${{ inputs.DOC_TAG }}
          allow_empty_commit: true
          force_orphan: false
          keep_files: true
